version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/WordPress
hooks:
  BeforeInstall:
    - location: wordpress/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: wordpress/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: wordpress/start_server.sh
    - location: wordpress/create_test_db.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: wordpress/stop_server.sh
      timeout: 300
      runas: root
